### ISSUE TITLE
Any luck on Ventura...?

### ISSUE THREAD

**Issue by andypiper** [noah-nash/joplin-arm64-darwin-guide#4]
I'm having a go at following the guide to build on Ventura but I'm hitting some issues with sharp and Keytar npm modules. Any ideas?

**Comment by noah-nash** [comment]
Off the top of my head I am not able to think of anything. I know that Ventura updated some stuff in regards to the MacOS Keychain, which could potentially be related to the keytar issues. If you had any logs or error messages to help troubleshoot that would be helpful.

Otherwise besides sharing the logs, I am still on Monterey so I don't know if I will be reproduce whatever issues there are. Sorry I can't be of more help.
